output: docs/generated

author: 21Gram Technology Kft.
author_url: https://21gram.hu

source_host_url: https://github.com/21GramConsulting/MediaType

title: Swift MediaType Docs

undocumented_text: ""
